[package]
name = "macroquad_sample_project"
version = "0.2.9"
authors = ["ZeroTix"]
edition = "2018"

[dependencies]
macroquad = "0.3.0-alpha"
quad-rand = "0.2.1"
getrandom = { version = "0.2", features = ["js"] }